#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [22]:
import pandas as pd

In [23]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [24]:
## Create a Series from dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [25]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [62]:
## Dataframe
## Create a Dataframe from a dictionary of list

data = {
    'Name': ['Daniel', 'John', 'Jack'],
    'Age': [35, 30, 45],
    'City': ['Zulia', 'New York', 'Florida']
}
df_example = pd.DataFrame(data)
print(df_example)
print(type(df_example))

     Name  Age      City
0  Daniel   35     Zulia
1    John   30  New York
2    Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [27]:
import numpy as np
np.array(df)

array([['Daniel', 35, 'Zulia'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [28]:
## Create a Data frame From a list of Dictionaries

data=[
    {'Name':'Daniel','Age':35,'City':'Zulia'},
    {'Name':'John','Age':34,'City':'Zulia'},
    {'Name':'Bappy','Age':32,'City':'Zulia'},
    {'Name':'JAck','Age':32,'City':'Zulia'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age   City
0  Daniel   35  Zulia
1    John   34  Zulia
2   Bappy   32  Zulia
3    JAck   32  Zulia
<class 'pandas.core.frame.DataFrame'>

In [29]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [33]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [36]:
### Accesing Data from Dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [38]:
df['Product Name']

0                                        iPhone 14 Pro
1                                     Dyson V11 Vacuum
2                                     Levi's 501 Jeans
3                                    The Da Vinci Code
4                              Neutrogena Skincare Set
                            ...
235    Nespresso Vertuo Next Coffee and Espresso Maker
236                          Nike Air Force 1 Sneakers
237             The Handmaid's Tale by Margaret Atwood
238               Sunday Riley Luna Sleeping Night Oil
239                         Yeti Rambler 20 oz Tumbler
Name: Product Name, Length: 240, dtype: object

In [45]:
df.loc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [48]:
df.iloc[0][2]

/var/folders/3s/m29z1_110292_z_4qc48n4sw0000gn/T/ipykernel_76318/2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Electronics'

In [53]:
## Accessing a specified element
df.at[2, 'Product Name']

"Levi's 501 Jeans"

In [56]:
## Accessing a specified element using iat
df.iat[2, 2]

'Clothing'

In [58]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [60]:
## Data Manipulation with Dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [66]:
## Adding a column
df_example['Salary'] = [50000, 60000, 70000]
df_example

     Name  Age      City  Salary
0  Daniel   35     Zulia   50000
1    John   30  New York   60000
2    Jack   45   Florida   70000

In [73]:
## Remove a column
df_example.drop('Salary', axis=1, inplace=True)

KeyError: "['Salary'] not found in axis"

In [75]:
df_example

     Name  Age      City
0  Daniel   35     Zulia
1    John   30  New York
2    Jack   45   Florida

In [79]:
## Add age to the column
df_example['Age'] = df_example['Age']+1
df_example

     Name  Age      City
0  Daniel   39     Zulia
1    John   34  New York
2    Jack   49   Florida

In [84]:
df_example.drop(0, inplace=True)

In [85]:
df_example

   Name  Age      City
1  John   34  New York
2  Jack   49   Florida

In [87]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [90]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
df.describe()